---
- name: Converge
  hosts: all
  roles:
    - role: arillso.traefik
  pre_tasks:
    - name: install docker-py
      package:
        name: docker-py
        state: present
    - name: add docker group
      group:
        name: docker
        state: present
  vars: {}
